### PR TITLE
Added ROS Assignment1 (kalyan)

### PR DESCRIPTION
**Pull request by kalyan-kumar**

### CODE REVIEW

**Comment by icyflame** [comment]
@kalyan-kumar 
- Please remove the `*.cpp~` files. These are backup files used by the editor. You can remove these files and then create a single commit.

**Comment by kalyan-kumar** [comment]
I removed the files. Could you review my pull request?

**Comment by icyflame** [comment]
@kalyan-kumar 
Your assignment does not follow the PS. Please read again and re-implement the parts which are not yet implemented.

This is for your referene:

image

**Comment by icyflame** [comment]
@kalyan-kumar 
Why did you close the PR?
Re-open this PR and push changes to this branch.

**Comment by kalyan-kumar** [comment]
I am unable to find my mistake.

**Comment by icyflame** [comment]
@kalyan-kumar 
You had to publish to the topic `/topic_squares` the squares of the numbers that are getting published on the `topic_numbers` branch. That was what the squares node was for. Currently, the squares node is not publishing anything at all.

**Comment by kalyan-kumar** [comment]
The program looks fine right? I am unable to understand why it is not publishing anything.

**Comment by icyflame** [comment]
@kalyan-kumar 
Your squares node has an issue. Speak with @barno0695 , he had similar code and it wasn't working, we then debugged it at the last meeting!

**Comment by kalyan-kumar** [comment]
It is working now. Could you review it?

**Comment by icyflame** [comment]
@kalyan-kumar 
Please note that inside the print node you have to right `topic_squares` before publishing the number published on that topic. Right now, you are printing `topic_numbers` in front of both the numbers. Rest of your application is fine.

**Comment by icyflame** [comment]
@kalyan-kumar
You had to edit the print node. Not the other two nodes.

**Comment by icyflame** [comment]
@kalyan-kumar 
You had to edit the `print` node. 

image

Before the number that gets printed from the squares topic, `topic_squares` should be written. This problem is in the print node, figure it out!

**Comment by kalyan-kumar** [comment]
It is working now.

**Pull request merged**
