### PR TITLE
Submission of assignment - Part II

### PR DESCRIPTION
**Pull request by dkuntal**
Previously diff was too big. I've removed extra files and submitting this again

### CODE REVIEW

**Comment by icyflame** [comment]
Too many errors, build failed.

screenshot from 2016-02-23 22 22 28

**Comment by dkuntal** [comment]
Closed because this one was functional for Catkin Workspace

**Comment by dkuntal** [comment]
Pull request #33 is for rosbuild. It's functional

**Comment by icyflame** [comment]
@dkuntal do not keep opening new pull requests. I did build this in the catkin workspace. And it was **not** working. Please fix this PR.

**Comment by dkuntal** [comment]
It was working in my system. There may be some other problem other than the
code. I have to find out

Thanks and regards,
Kuntal Das

2nd Year Undergraduate Student
Department of Industrial and Systems Engineering
Indian Institute of Technology, Kharagpur

**Comment by dkuntal** [comment]
I cannot find any problem.
And also there was no difference with other accepted Pull Requests. I've checked the differences using diffchecker.com

**Comment by icyflame** [comment]
@dkuntal Can you run the package in your catkin workspace **now**? I am still getting the same error. (No code has changed, so that is expected)

**Comment by icyflame** [comment]
Issue is CMP0002. Check [this](https://github.com/auviitkgp/ros-sandbox/pull/9#issuecomment-78117355). Rename your executables to something like: `<username>_numbers`, `<username>_print`, etc.

**Pull request closed without merging**
