### PR TITLE
Pull request from pranaypratyush

### PR DESCRIPTION
**Pull request by pranaypratyush**
Completed the whole assingnement in a single go. Adding my work in the branch

'pranaypratyush' at assingnment1/pranaypratyush_print_squares.

### CODE REVIEW

**Comment by icyflame** [comment]
@pranaypratyush 
Good work!
- Change the commit message to something more concise. You may add the description in the description field. But keep the first line concise. (Refer to already merged commits for examples) Read [this](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) to learn about better commit messages.

**Comment by pranaypratyush** [comment]
I re wrote the commit and also increased the readability of the code.

**Comment by icyflame** [comment]
@pranaypratyush
I don't see the re-worded commit.

**Comment by pranaypratyush** [comment]
How? I can see it. And everything is up-to-date.

**Comment by icyflame** [comment]
@pranaypratyush
Reword to commit to "Added assignment 1 (Pranay Pratyush)".
The present message, `Merge branch` does not tell anyone anything about what was merged.

**Comment by pranaypratyush** [comment]
it should be done now..

**Pull request merged**
