### PR TITLE
Completed assignment 1 -  to print squares at 1Hz

### PR DESCRIPTION
**Pull request by Shaswat27**
Coded in roscpp, Catkin package containing 3 files - Numbers.cpp (to publish integers), Square.cpp (to subscribe and square the published integers and publish them to another topic) and Print.cpp (to display numbers and squares by publishing to both topics).

### CODE REVIEW

**Comment by icyflame** [comment]
Read up on `.gitignore` and commit again after adding an appropriate
`.gitignore` that ignores the `.cpp~` files. These are temporary files used
by the editor. Use either `git reset` or `git commit --amend` followed by
`git push --force`.

**Comment by Shaswat27** [comment]
Can't I just delete the .cpp~ files from the original repository? 
Is the rest of it fine?

**Comment by Shaswat27** [comment]
temps deleted

**Comment by Shaswat27** [comment]
deleted temps, without gitignore though
using git rm --cached **/*~
have created a global gitignore case for **/*~

**Comment by icyflame** [comment]
- This won't do. You have to commit an appropriate `gitignore` file so we are convinced you have learnt it. Further, if you just delete it from here, the next time you open the file in an editor, the files will be added again. And this is undesirable behaviour. The `gitignore` file exists so that there is as universal standard behaviour across machines and repositories.  
- Also, remove the last two commits. You won't need these two commits, once you have added an appropriate gitignore file.

**Comment by Shaswat27** [comment]
i'll commit the .gitignore file tomorrow.

**Comment by icyflame** [comment]
@Shaswat27 

A commit that was already on master has come into this PR. Please rectify that. 

Everything else is fine. Good going, :+1:

**Comment by Shaswat27** [comment]
history fixed

**Comment by icyflame** [comment]
Looks good :+1:

**Pull request merged**
