### PR TITLE
Added assignment by parthamishra1996

### PR DESCRIPTION
**Pull request by parthamishra1996**
Creating pull request

### CODE REVIEW

**Comment by icyflame** [comment]
@parthamishra1996 Your submission could not be built. The error message:

```shell
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkin_package.cmake:296 (message):
  catkin_package() include dir 'include' does not exist relative to
  '/home/siddharth/catkin_ws/src/ros-sandbox/assignment_1/parthamishra1996_print_squares'
Call Stack (most recent call first):
  /opt/ros/indigo/share/catkin/cmake/catkin_package.cmake:98 (_catkin_package)
  ros-sandbox/assignment_1/parthamishra1996_print_squares/CMakeLists.txt:82 (catkin_package)
```

**Comment by parthamishra1996** [comment]
it is not showing error in my machine but still i have editted to exclude that include... @icyflame is it okay now?

**Comment by icyflame** [comment]
@parthamishra1996 Please note that you must uncomment that line only if your project consists of header files. I will check the build status and get back to you.

**Comment by icyflame** [comment]
@parthamishra1996 
Looks good :+1: 

**Some suggestions:**
- **CMP0002:** This is the reason you were asked to rename the executables to something unique. You can read more about this [here](http://www.cmake.org/cmake/help/v3.0/policy/CMP0002.html). So, it is always advisable to name your executables uniquely.
- **Your development history is non-existent.** It is mentioned in the PS that you must record your development history using Git. (After completing a major part of the project, you must make a commit so as to make sure that you can revert back to this point, in case you add some code that breaks your project afterwards. This is also good [practise](http://programmers.stackexchange.com/questions/83837/when-to-commit-code).) I will merge this project because it was the first assignment. From the next time, merges with only one commit on the development history (As in your GH repo `username_print_squares`, in this case) won't be merged.

**Pull request merged**
