### PR TITLE
Added assignment by vermaparth

### PR DESCRIPTION
**Pull request by vermaparth**

### CODE REVIEW

**Comment by icyflame** [comment]
Remove temp files and ping here when done.

**Comment by icyflame** [comment]
Same problem as in #31.

I have tried building the master branch of this repository and it works fine for me, so this is not an issue with my computer. Run it again and **read the error message** and try to figure out what the problem is.

cc @dkuntal

**Comment by icyflame** [comment]
Issue is CMP0002. Check [this](https://github.com/auviitkgp/ros-sandbox/pull/9#issuecomment-78117355). Rename your executables to something like: `<username>_numbers`, `<username>_print`, etc.

**Comment by icyflame** [comment]
@vermaparth Write [better](http://chris.beams.io/posts/git-commit/) commit messages.

**Comment by icyflame** [comment]
@vermaparth You have not changed name of the executables, that has to be done in the cmakelists file.

**Comment by vermaparth** [comment]
Changed the name of executables in CMakeLists.txt

**Comment by icyflame** [comment]
@vermaparth Build fails. Always build on computer before commenting here.

**Pull request closed without merging**
