### PR TITLE
added assignment(lovishpuri)

### PR DESCRIPTION
**Pull request by lovishpuri**
Added my catkin package

### CODE REVIEW

**Comment by icyflame** [comment]
@lovishpuri 
Your PR was good. You can re-open it.

**Comment by icyflame** [comment]
@lovishpuri 
Your package could not be built. This is the error that was encountered:

```shell
-- ==> add_subdirectory(ros-sandbox/assignment_1/lovishpuri_print_squares)
-- Using these message generators: gencpp;genlisp;genpy
CMake Error at /opt/ros/indigo/share/genmsg/cmake/genmsg-extras.cmake:91 (message):
  add_message_files() directory not found:
  /home/siddharth/catkin_ws/src/ros-sandbox/assignment_1/lovishpuri_print_squares/msg
Call Stack (most recent call first):
  ros-sandbox/assignment_1/lovishpuri_print_squares/CMakeLists.txt:12 (add_message_files)
```

**Comment by lovishpuri** [comment]
Added two more commits.

**Comment by icyflame** [comment]
@lovishpuri 
Please edit your project name in the `package.xml` file.

**Comment by icyflame** [comment]
@lovishpuri 
Please fix this error:

```shell
/home/siddharth/catkin_ws/src/ros-sandbox/assignment_1/lovishpuri_print_squares/src/print_lovishpuri.cpp:2:30: fatal error: std_msgs/int64.msg: No such file or directory
 #include "std_msgs/int64.msg"
```

**Always ensure that you package build befoer pushing to GitHub.**

**Comment by lovishpuri** [comment]
Please help me fix this error. I have tried to google it but found
nothing which solved my error. I don't know how and where to add
int64.msg(maybe it's a foolish question). Other people have simply
removed the genmsg from their package to avoid this error, but I am
not sure it will run successfully.

On 3/21/15, Siddharth Kannan <notifications@github.com> wrote:
> @lovishpuri
> Please fix this error:
>
> ```shell
> /home/siddharth/catkin_ws/src/ros-sandbox/assignment_1/lovishpuri_print_squares/src/print_lovishpuri.cpp:2:30:
> fatal error: std_msgs/int64.msg: No such file or directory
>  #include "std_msgs/int64.msg"
> ```
>
> **Always ensure that you package build befoer pushing to GitHub.**
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/auviitkgp/ros-sandbox/pull/23#issuecomment-84266976


-- 
Lovish

**Comment by icyflame** [comment]
@lovishpuri 
Note that by using the `int64.msg` you indicate that you have a ROS message type by the name "int64". You must try to use one of the inbuilt datatypes. For using these datatypes, you need to include their "header" files, not the message files.

**Comment by lovishpuri** [comment]
Added some more commits.

**Comment by icyflame** [comment]
@lovishpuri 

The numbers node is not publishing to the topic it should publish to.

**Pull request merged**
