### PR TITLE
Add assignment 1 problem statement

### PR DESCRIPTION
**Pull request by routeaccess**
- Create a new folder for assignment 1 submissions.
- Add problem statement and submission instructions.

Signed-off-by: Nevin Valsaraj <nevin.valsaraj32@gmail.com>

### CODE REVIEW

**Comment by icyflame** [comment]
@routeaccess Don't you think the name of the package should be `print_squares_<github-username>` ?

If the name of the package is `<github-username>`, before the next assignment they will have to rename the package or delete it.

**Comment by routeaccess** [comment]
>If the name of the package is `<github-username>`, before the next assignment they will have to rename the package or delete it.

Good thinking. But I think it would be better to add assignment name as a suffix  - this aggregates all assignments with a common prefix and would also help with tab completion in a terminal. This would make the naming pattern `<github_username>_print_squares`

**Comment by icyflame** [comment]
Check the new PR, the nameing pattern for the packages is `print_squares_username`. This will be easy even in tab completion! And we can simply take care of them by the alphabetical order of their usernames.

And `<github-username>_print_squares` will aggregate all the packages with a common suffix! Not a common prefix!

**Comment by routeaccess** [comment]
> And `<github-username>_print_squares` will aggregate all the packages with a common suffix! Not a common prefix!

It aggregates all assignment packages with a common prefix in the user's workspace - prefix being <username> - and using this particular prefix helps identify which package belongs to which contributor without checking the logs.

**Pull request merged**
