### PR TITLE
Added assignment_1.

### PR DESCRIPTION
**Pull request by pranaikumar**
Added my first catkin assignment at last.Working as expected.

### CODE REVIEW

**Comment by icyflame** [comment]
@pranaikumar 
In the numbers node, you have to print natural numbers. (starting from 1).

Not random numbers, as you have done. Please correct this.

**Comment by pranaikumar** [comment]
Done with it. Sorry about reading the problem statement wrong.

**Comment by pranaikumar** [comment]
Now it prints numbers from 1...

**Comment by icyflame** [comment]
@pranaikumar 
Please reword the commit https://github.com/pranaikumar/ros-sandbox/commit/27e32f9e08aa3e395263d9d151a853635393f853. Move the description of the commit to two lines below the first line.

Example Commit message:
```shell
Changed the numbers.cpp file

- It used to print random numbers before
- Now, it prints natural numbers sequentially, starting from 1
```

**Comment by pranaikumar** [comment]
Rewording done

**Comment by icyflame** [comment]
@pranaikumar 
The last three commits are redundant and seem to be doing the same thing. Squash them into one commit.

**Comment by icyflame** [comment]
Closed in favour of #25

**Pull request closed without merging**
