### PR TITLE
Add the problem statement for assignment 1

### PR DESCRIPTION
**Pull request by icyflame**
Make the problem statement more verbose.

### CODE REVIEW

**Comment by routeaccess** [comment]
@icyflame It is a good practice to not have merge commits within a PR. Please rebase your commits with the `master` branch HEAD instead of merging.

**Comment by routeaccess** [comment]
Please resolve the following issues :

- Arbitrary nested bullet points are present in the instructions part
- Extra indentation leading to quoting of text in the logistics and submission instructions.
- Please stick to unordered lists in development process rather than mixing it up.
- Please change naming format of packages from `print_squares_<username>` to `<username>_print_squares` as discussed before.
- Consider revising the language of the second (un-necessarily nested) point under logistics.

Use the [rich diff](https://github.com/auviitkgp/ros-sandbox/pull/2/files?short_path=638b600#diff-638b600c59d9517131ea5564734230c3) for reviewing markdown files.

**Comment by icyflame** [comment]
Fixed a lot of the issues with the last push.

**Comment by routeaccess** [comment]
Please resolve the following issues:

- the commit history of all the changes made via this pull request is not required / unhelpful. Please squash these commits into a single commit.
- in 'final submission instructions, please update the package name.
- revise the language of second point under 'development process'

> must not have any of the documentation that is there in the code

Please change this to 'must not copy any of the documentation present in the code'

**Comment by icyflame** [comment]
Commits squashed into one. Edited point 2 as suggested above.

**Pull request merged**
