### PR TITLE
added assignment by aranya dan

### PR DESCRIPTION
**Pull request by aranyadan**
https://github.com/aranyadan/aranyadan_print_squares

### CODE REVIEW

**Comment by icyflame** [comment]
- Squash the last two commits (regarding temp files) into one.
- ideally, these commits should not be here. You should add such unwanted
files to the `.gitignore` file. Read up about this and commit an
appropriate `.gitignore` file for this project.
- Add the link to your git repository consisting of the development
history. (The github repo `username/username_print_squares`)

**Comment by icyflame** [comment]
- Squash the last two commits (regarding temp files) into one.
- ideally, these commits should not be here. You should add such unwanted
files to the `.gitignore` file. Read up about this and commit an
appropriate `.gitignore` file for this project.
- Add the link to your github repository, in the description, consisting the development
history. (The github repo `username/username_print_squares`)

**Comment by aranyadan** [comment]
what do you mean by description? is it the commit message? currently reading up gitignore

**Comment by icyflame** [comment]
Add the link to your github repository as described in the README, in the
description of this Pull Request. (Final submissions include a github
repository apart from this PR. )

Sorry, that sentence was misformed earlier. I believe it must be clear now.

**Comment by icyflame** [comment]
@aranyadan 

- Note that the link of the github repo must be added in the **description** of the PR. The name of the PR was fine in the earlier case, please revert it back to that. 
- The github repo must be at `username/username_print_squares`. So, in your case the repo must be at `aranyadan/aranyadan_print_squares`. Presently, you have simply given the link of the assignment folder at your fork. 
- You must commit an appropriate `.gitignore` file. Once you do that you will no longer need the `remove temp files ` commit. Thus, the squashed commit mustn't be there in the history. Instead, a commit adding the new gitignore file must be present.

**Comment by icyflame** [comment]
- Reword your second commit to mean something more meaningful that `Squashed commit of the following`.

**Comment by aranyadan** [comment]
squashed all and changed commit message

**Comment by icyflame** [comment]
@aranyadan 
You must add only your files in this PR. Your PR shows all the changes made on the master branch in the `Files Changes` tab. Rectify this by rebasing your changes to the latest master.

**Comment by icyflame** [comment]
Closed in favour of #18

**Pull request closed without merging**
