### PR TITLE
Added Assignment1 (Sandeep Sharma)

### PR DESCRIPTION
**Pull request by sandeepsharma-kgp**
Printing numbers and its squares

### CODE REVIEW

**Comment by icyflame** [comment]
@sandeepsharma-kgp
- Please remove the `*.cpp~` files from your directory. These are backup files that are used by your editor.

**Comment by sandeepsharma-kgp** [comment]
I did what was told.

**Comment by icyflame** [comment]
@sandeepsharma-kgp 
- Please squash the last three commits into one, for a cleaner history.

**Comment by sandeepsharma-kgp** [comment]
@icyflame Please check is it done?

**Pull request merged**
